### ISSUE TITLE
Anchor system and UI disappeared?

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armory2d#2]
1:
What exactly does the anchor system do? I’ve looked at UI examples and enabled different anchor options ,but I can’t tell that it does anything at all. 

2:
I had the UI completely disappear and had to close Armorui. Not sure what I was doing at the time and I tried to get it to do it again ,but couldn’t. I know I had added a “text”, deleted it, and then when I clicked to add “button” it happened.
   
3:
Scaling/ moving with mouse the response time seems slow.

**Comment by AFWSI** [comment]
OK, I got it to disappear several more times. It doesn't always do it ,but it did it more times than not.

What I was doing was making text box outside of canvas box, enabling left for anchor, remove the text, and then select add button.

![armorui_text_outside](https://user-images.githubusercontent.com/24877571/38455673-376ff044-3a41-11e8-8779-4d2078502fbe.jpg)

![armorui_disappear](https://user-images.githubusercontent.com/24877571/38455676-3ea65dee-3a41-11e8-8a34-eb2ab502fc7a.jpg)

**Comment by luboslenco** [comment]
Seems to be good now! Scaling text items can be slow for the first time because it generates the font atlas for given text size.

Anchors play role when the game resolution changes, ie. with Bottom-Right anchor the item is glued to that corner even when resolution increases. Should maybe change the naming to pivot.:)
